version: '3'

services:
  php:
    container_name: ${DOCKER_NAMESPACE}-php
    build:
      context: ./docker/php
      args:
        uid: ${DOCKER_UID:-1000}
    volumes:
      - ./:/srv/www
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  nginx:
    container_name: ${DOCKER_NAMESPACE}-nginx
    image: nginx:latest
    ports:
      - ${DOCKER_HTTP_PORT:-0}:80
    volumes:
      - ./:/srv/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf